### ISSUE TITLE
在私聊环境中是否可以不必显示“引用内容”~

### ISSUE THREAD

**Issue by i-iooi-i** [slippersheepig/chatgpt-telegram-bot#4]
感动哭了大佬~
终于找到了一个可以联系上下文回答问题，而不是那种看上去不太聪明的降智版chatgpt了。😂

拉取的是：
![image](https://user-images.githubusercontent.com/1827701/216792158-a62c89ab-d4c2-4a1d-b338-abf958b8d36c.png)
这个api版本的镜像，使用体验非常愉快~

在使用过程中提两点体验上的建议哈：

![image](https://user-images.githubusercontent.com/1827701/216792203-9343ebd8-215b-4037-afab-9f1b341e5585.png)
1. 是否考虑在私人聊天的环境下，不必显示引用内容作为回复呢？已制造一种沉浸式的聊天，就像人与人直接聊天的体验。感觉这种引用的方式，放在多人群聊的环境中，为了避免回复错消息，引用内容作为回复更合适一些。

2. 未来是否考虑加入群聊的功能？比如大家在群里触发关键字（比如给chatgpt自定义个名字），群里有人@这个名字并且输入需要提问的问题，以唤醒chatgpt出来回答问题之类的。

总之很棒，非常感谢！

**Comment by slippersheepig** [comment]
Sorry, but the api version is unusable and my coding is very bad. Close this issue and hope ChatGPT API will be released someday
